export type ParamEncoding = 'int1x7' | 'int2x4' | 'int4x4';

export interface StageParamSchema {
  key: string;
  label: string;
  rawIndex: number;
  size: ParamEncoding;
  min: number;
  max: number;
  offset: number;
}

export const BOOSTER_PARAM_SCHEMA: readonly StageParamSchema[] = [
  { key: 'type', label: 'Type', rawIndex: 1, size: 'int1x7', min: 0, max: 22, offset: 0 },
  { key: 'drive', label: 'Drive', rawIndex: 2, size: 'int1x7', min: 0, max: 120, offset: 0 },
  { key: 'bottom', label: 'Bottom', rawIndex: 3, size: 'int1x7', min: -50, max: 50, offset: 50 },
  { key: 'tone', label: 'Tone', rawIndex: 4, size: 'int1x7', min: -50, max: 50, offset: 50 },
  { key: 'solo_sw', label: 'Solo SW', rawIndex: 5, size: 'int1x7', min: 0, max: 1, offset: 0 },
  { key: 'solo_level', label: 'Solo Level', rawIndex: 6, size: 'int1x7', min: 0, max: 100, offset: 0 },
  { key: 'effect_level', label: 'Effect Level', rawIndex: 7, size: 'int1x7', min: 0, max: 100, offset: 0 },
  { key: 'direct_mix', label: 'Direct Mix', rawIndex: 8, size: 'int1x7', min: 0, max: 100, offset: 0 },
];

export const DELAY_PARAM_SCHEMA: readonly StageParamSchema[] = [
  { key: 'type', label: 'Type', rawIndex: 1, size: 'int1x7', min: 0, max: 7, offset: 0 },
  { key: 'time', label: 'Time', rawIndex: 2, size: 'int4x4', min: 1, max: 2000, offset: 0 },
  { key: 'feedback', label: 'Feedback', rawIndex: 6, size: 'int1x7', min: 0, max: 100, offset: 0 },
  { key: 'high_cut', label: 'High Cut', rawIndex: 7, size: 'int1x7', min: 0, max: 14, offset: 0 },
  { key: 'effect_level', label: 'Effect Level', rawIndex: 8, size: 'int1x7', min: 0, max: 120, offset: 0 },
  { key: 'direct_level', label: 'Direct Level', rawIndex: 9, size: 'int1x7', min: 0, max: 100, offset: 0 },
  { key: 'tap_time', label: 'Tap Time', rawIndex: 10, size: 'int1x7', min: 0, max: 100, offset: 0 },
  { key: 'mod_rate', label: 'Mod Rate', rawIndex: 11, size: 'int1x7', min: 0, max: 100, offset: 0 },
  { key: 'mod_depth', label: 'Mod Depth', rawIndex: 12, size: 'int1x7', min: 0, max: 100, offset: 0 },
  { key: 'lpf', label: 'LPF', rawIndex: 13, size: 'int1x7', min: 0, max: 1, offset: 0 },
  { key: 'filter', label: 'Filter', rawIndex: 14, size: 'int1x7', min: 0, max: 1, offset: 0 },
  { key: 'feedback_phase', label: 'Feedback Phase', rawIndex: 15, size: 'int1x7', min: 0, max: 1, offset: 0 },
  { key: 'delay_phase', label: 'Delay Phase', rawIndex: 16, size: 'int1x7', min: 0, max: 1, offset: 0 },
  { key: 'mod_sw', label: 'Mod SW', rawIndex: 17, size: 'int1x7', min: 0, max: 1, offset: 0 },
];

export const REVERB_PARAM_SCHEMA: readonly StageParamSchema[] = [
  { key: 'type', label: 'Type', rawIndex: 1, size: 'int1x7', min: 0, max: 4, offset: 0 },
  { key: 'layer_mode', label: 'Layer Mode', rawIndex: 2, size: 'int1x7', min: 0, max: 2, offset: 0 },
  { key: 'time', label: 'Time', rawIndex: 3, size: 'int1x7', min: 1, max: 100, offset: -1 },
  { key: 'pre_delay', label: 'Pre Delay', rawIndex: 4, size: 'int4x4', min: 0, max: 500, offset: 0 },
  { key: 'low_cut', label: 'Low Cut', rawIndex: 8, size: 'int1x7', min: 0, max: 17, offset: 0 },
  { key: 'high_cut', label: 'High Cut', rawIndex: 9, size: 'int1x7', min: 0, max: 14, offset: 0 },
  { key: 'density', label: 'Density', rawIndex: 10, size: 'int1x7', min: 0, max: 10, offset: 0 },
  { key: 'effect_level', label: 'Effect Level', rawIndex: 11, size: 'int1x7', min: 0, max: 100, offset: 0 },
  { key: 'direct_level', label: 'Direct Level', rawIndex: 12, size: 'int1x7', min: 0, max: 100, offset: 0 },
  { key: 'spring_color', label: 'Spring Color', rawIndex: 13, size: 'int1x7', min: 0, max: 100, offset: 0 },
];

export const FX_PARAM_SCHEMAS_BY_TYPE: ReadonlyArray<readonly StageParamSchema[]> = [
  [
    { key: 'mode', label: 'Mode', rawIndex: 1, size: 'int1x7', min: 0, max: 1, offset: 0 },
    { key: 'polarity', label: 'Polarity', rawIndex: 2, size: 'int1x7', min: 0, max: 1, offset: 0 },
    { key: 'sens', label: 'Sens', rawIndex: 3, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'freq', label: 'Freq', rawIndex: 4, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'peak', label: 'Peak', rawIndex: 5, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 6, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'effect_level', label: 'Effect Level', rawIndex: 7, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'mode', label: 'Mode', rawIndex: 8, size: 'int1x7', min: 0, max: 1, offset: 0 },
    { key: 'freq', label: 'Freq', rawIndex: 9, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'peak', label: 'Peak', rawIndex: 10, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'rate', label: 'Rate', rawIndex: 11, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'depth', label: 'Depth', rawIndex: 12, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 13, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'effect_level', label: 'Effect Level', rawIndex: 14, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'wah_type', label: 'Wah Type', rawIndex: 15, size: 'int1x7', min: 0, max: 5, offset: 0 },
    { key: 'pedal_position', label: 'Pedal Position', rawIndex: 16, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'pedal_min', label: 'Pedal Min', rawIndex: 17, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'pedal_max', label: 'Pedal Max', rawIndex: 18, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'effect_level', label: 'Effect Level', rawIndex: 19, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 20, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'type', label: 'Type', rawIndex: 21, size: 'int1x7', min: 0, max: 6, offset: 0 },
    { key: 'sustain', label: 'Sustain', rawIndex: 22, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'attack', label: 'Attack', rawIndex: 23, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'tone', label: 'Tone', rawIndex: 24, size: 'int1x7', min: -50, max: 50, offset: 50 },
    { key: 'level', label: 'Level', rawIndex: 25, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'type', label: 'Type', rawIndex: 26, size: 'int1x7', min: 0, max: 2, offset: 0 },
    { key: 'attack', label: 'Attack', rawIndex: 27, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'threshold', label: 'Threshold', rawIndex: 28, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'ratio', label: 'Ratio', rawIndex: 29, size: 'int1x7', min: 0, max: 17, offset: 0 },
    { key: 'release', label: 'Release', rawIndex: 30, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'level', label: 'Level', rawIndex: 31, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: '31hz', label: '31Hz', rawIndex: 32, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: '62hz', label: '62Hz', rawIndex: 33, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: '125hz', label: '125Hz', rawIndex: 34, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: '250hz', label: '250Hz', rawIndex: 35, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: '500hz', label: '500Hz', rawIndex: 36, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: '1khz', label: '1kHz', rawIndex: 37, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: '2khz', label: '2kHz', rawIndex: 38, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: '4khz', label: '4kHz', rawIndex: 39, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: '8khz', label: '8kHz', rawIndex: 40, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: '16khz', label: '16kHz', rawIndex: 41, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: 'level', label: 'Level', rawIndex: 42, size: 'int1x7', min: -20, max: 20, offset: 20 },
  ],
  [
    { key: 'low_cut', label: 'Low Cut', rawIndex: 43, size: 'int1x7', min: 0, max: 17, offset: 0 },
    { key: 'low_gain', label: 'Low Gain', rawIndex: 44, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: 'lowmid_freq', label: 'Low Mid Freq', rawIndex: 45, size: 'int1x7', min: 0, max: 27, offset: 0 },
    { key: 'lowmid_q', label: 'Low Mid Q', rawIndex: 46, size: 'int1x7', min: 0, max: 5, offset: 0 },
    { key: 'lowmid_gain', label: 'Low Mid Gain', rawIndex: 47, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: 'highmid_freq', label: 'High Mid Freq', rawIndex: 48, size: 'int1x7', min: 0, max: 27, offset: 0 },
    { key: 'highmid_q', label: 'High Mid Q', rawIndex: 49, size: 'int1x7', min: 0, max: 5, offset: 0 },
    { key: 'highmid_gain', label: 'High Mid Gain', rawIndex: 50, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: 'high_gain', label: 'High Gain', rawIndex: 51, size: 'int1x7', min: -20, max: 20, offset: 20 },
    { key: 'high_cut', label: 'High Cut', rawIndex: 52, size: 'int1x7', min: 0, max: 14, offset: 0 },
    { key: 'level', label: 'Level', rawIndex: 53, size: 'int1x7', min: -20, max: 20, offset: 20 },
  ],
  [
    { key: 'type', label: 'Type', rawIndex: 54, size: 'int1x7', min: 0, max: 7, offset: 0 },
    { key: 'low', label: 'Low', rawIndex: 55, size: 'int1x7', min: -50, max: 50, offset: 50 },
    { key: 'high', label: 'High', rawIndex: 56, size: 'int1x7', min: -50, max: 50, offset: 50 },
    { key: 'level', label: 'Level', rawIndex: 57, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'body', label: 'Body', rawIndex: 58, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'sens', label: 'Sens', rawIndex: 59, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'rise_time', label: 'Rise Time', rawIndex: 60, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'level', label: 'Level', rawIndex: 61, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'wave', label: 'Wave', rawIndex: 62, size: 'int1x7', min: 0, max: 1, offset: 0 },
    { key: 'cutoff', label: 'Cutoff', rawIndex: 63, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'resonance', label: 'Resonance', rawIndex: 64, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'filter_sens', label: 'Filter Sens', rawIndex: 65, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'filter_decay', label: 'Filter Decay', rawIndex: 66, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'filter_depth', label: 'Filter Depth', rawIndex: 67, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'synth_level', label: 'Synth Level', rawIndex: 68, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 69, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'range', label: 'Range', rawIndex: 70, size: 'int1x7', min: 0, max: 3, offset: 0 },
    { key: 'effect_level', label: 'Effect Level', rawIndex: 71, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 72, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'voice', label: 'Voice', rawIndex: 73, size: 'int1x7', min: 0, max: 1, offset: 0 },
    { key: 'mode1', label: 'Mode1', rawIndex: 74, size: 'int1x7', min: 0, max: 3, offset: 0 },
    { key: 'pitch1', label: 'Pitch1', rawIndex: 75, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'fine1', label: 'Fine1', rawIndex: 76, size: 'int1x7', min: -50, max: 50, offset: 50 },
    { key: 'pre_delay1', label: 'Pre Delay1', rawIndex: 77, size: 'int4x4', min: 0, max: 300, offset: 0 },
    { key: 'level1', label: 'Level1', rawIndex: 81, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'mode2', label: 'Mode2', rawIndex: 82, size: 'int1x7', min: 0, max: 3, offset: 0 },
    { key: 'pitch2', label: 'Pitch2', rawIndex: 83, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'fine2', label: 'Fine2', rawIndex: 84, size: 'int1x7', min: -50, max: 50, offset: 50 },
    { key: 'pre_delay2', label: 'Pre Delay2', rawIndex: 85, size: 'int4x4', min: 0, max: 300, offset: 0 },
    { key: 'level2', label: 'Level2', rawIndex: 89, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'feedback1', label: 'Feedback1', rawIndex: 90, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 91, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'voice', label: 'Voice', rawIndex: 92, size: 'int1x7', min: 0, max: 1, offset: 0 },
    { key: 'harmony1', label: 'Harmony1', rawIndex: 93, size: 'int1x7', min: 0, max: 29, offset: 0 },
    { key: 'pre_delay1', label: 'Pre Delay1', rawIndex: 94, size: 'int4x4', min: 0, max: 300, offset: 0 },
    { key: 'level1', label: 'Level1', rawIndex: 98, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'harmony2', label: 'Harmony2', rawIndex: 99, size: 'int1x7', min: 0, max: 29, offset: 0 },
    { key: 'pre_delay2', label: 'Pre Delay2', rawIndex: 100, size: 'int4x4', min: 0, max: 300, offset: 0 },
    { key: 'level2', label: 'Level2', rawIndex: 104, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'feedback1', label: 'Feedback1', rawIndex: 105, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 106, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'c1', label: 'C1', rawIndex: 107, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'db1', label: 'Db1', rawIndex: 108, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'd1', label: 'D1', rawIndex: 109, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'eb1', label: 'Eb1', rawIndex: 110, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'e1', label: 'E1', rawIndex: 111, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'f1', label: 'F1', rawIndex: 112, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'fs1', label: 'F#1', rawIndex: 113, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'g1', label: 'G1', rawIndex: 114, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'ab1', label: 'Ab1', rawIndex: 115, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'a1', label: 'A1', rawIndex: 116, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'bb1', label: 'Bb1', rawIndex: 117, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'b1', label: 'B1', rawIndex: 118, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'c2', label: 'C2', rawIndex: 119, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'db2', label: 'Db2', rawIndex: 120, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'd2', label: 'D2', rawIndex: 121, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'eb2', label: 'Eb2', rawIndex: 122, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'e2', label: 'E2', rawIndex: 123, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'f2', label: 'F2', rawIndex: 124, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'fs2', label: 'F#2', rawIndex: 125, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'g2', label: 'G2', rawIndex: 126, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'ab2', label: 'Ab2', rawIndex: 127, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'a2', label: 'A2', rawIndex: 128, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'bb2', label: 'Bb2', rawIndex: 129, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'b2', label: 'B2', rawIndex: 130, size: 'int1x7', min: -24, max: 24, offset: 24 },
  ],
  [
    { key: 'type', label: 'Type', rawIndex: 131, size: 'int1x7', min: 0, max: 3, offset: 0 },
    { key: 'bass', label: 'Bass', rawIndex: 132, size: 'int1x7', min: -50, max: 50, offset: 50 },
    { key: 'middle', label: 'Middle', rawIndex: 133, size: 'int1x7', min: -50, max: 50, offset: 50 },
    { key: 'middle_freq', label: 'Middle Freq', rawIndex: 134, size: 'int1x7', min: 0, max: 27, offset: 0 },
    { key: 'treble', label: 'Treble', rawIndex: 135, size: 'int1x7', min: -50, max: 50, offset: 50 },
    { key: 'presence', label: 'Presence', rawIndex: 136, size: 'int1x7', min: -50, max: 50, offset: 50 },
    { key: 'level', label: 'Level', rawIndex: 137, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'type', label: 'Type', rawIndex: 138, size: 'int1x7', min: 0, max: 3, offset: 0 },
    { key: 'rate', label: 'Rate', rawIndex: 139, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'depth', label: 'Depth', rawIndex: 140, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'manual', label: 'Manual', rawIndex: 141, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'resonance', label: 'Resonance', rawIndex: 142, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'step_rate', label: 'Step Rate', rawIndex: 143, size: 'int1x7', min: -1, max: 100, offset: 1 },
    { key: 'effect_level', label: 'Effect Level', rawIndex: 144, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 145, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'rate', label: 'Rate', rawIndex: 146, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'depth', label: 'Depth', rawIndex: 147, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'manual', label: 'Manual', rawIndex: 148, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'resonance', label: 'Resonance', rawIndex: 149, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'low_cut', label: 'Low Cut', rawIndex: 150, size: 'int1x7', min: 0, max: 10, offset: 0 },
    { key: 'effect_level', label: 'Effect Level', rawIndex: 151, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 152, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'wave_shape', label: 'Wave Shape', rawIndex: 153, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'rate', label: 'Rate', rawIndex: 154, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'depth', label: 'Depth', rawIndex: 155, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'level', label: 'Level', rawIndex: 156, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'rate', label: 'Rate', rawIndex: 157, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'depth', label: 'Depth', rawIndex: 158, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'level', label: 'Level', rawIndex: 159, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'rate', label: 'Rate', rawIndex: 160, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'depth', label: 'Depth', rawIndex: 161, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'level', label: 'Level', rawIndex: 162, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'pattern', label: 'Pattern', rawIndex: 163, size: 'int1x7', min: 0, max: 19, offset: 0 },
    { key: 'rate', label: 'Rate', rawIndex: 164, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'trigger_sens', label: 'Trigger Sens', rawIndex: 165, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'effect_level', label: 'Effect Level', rawIndex: 166, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 167, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'rate', label: 'Rate', rawIndex: 168, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'depth', label: 'Depth', rawIndex: 169, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'level', label: 'Level', rawIndex: 170, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'mode', label: 'Mode', rawIndex: 171, size: 'int1x7', min: 0, max: 1, offset: 0 },
    { key: 'frequency', label: 'Frequency', rawIndex: 172, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'effect_level', label: 'Effect Level', rawIndex: 173, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 174, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'mode', label: 'Mode', rawIndex: 175, size: 'int1x7', min: 0, max: 1, offset: 0 },
    { key: 'vowel1', label: 'Vowel1', rawIndex: 176, size: 'int1x7', min: 0, max: 4, offset: 0 },
    { key: 'vowel2', label: 'Vowel2', rawIndex: 177, size: 'int1x7', min: 0, max: 4, offset: 0 },
    { key: 'sens', label: 'Sens', rawIndex: 178, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'rate', label: 'Rate', rawIndex: 179, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'depth', label: 'Depth', rawIndex: 180, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'manual', label: 'Manual', rawIndex: 181, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'level', label: 'Level', rawIndex: 182, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'xover_frequency', label: 'X-Over Frequency', rawIndex: 183, size: 'int1x7', min: 0, max: 16, offset: 0 },
    { key: 'low_rate', label: 'Low Rate', rawIndex: 184, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'low_depth', label: 'Low Depth', rawIndex: 185, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'low_pre_delay', label: 'Low Pre Delay', rawIndex: 186, size: 'int1x7', min: 0, max: 80, offset: 0 },
    { key: 'low_level', label: 'Low Level', rawIndex: 187, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'high_rate', label: 'High Rate', rawIndex: 188, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'high_depth', label: 'High Depth', rawIndex: 189, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'high_pre_delay', label: 'High Pre Delay', rawIndex: 190, size: 'int1x7', min: 0, max: 80, offset: 0 },
    { key: 'high_level', label: 'High Level', rawIndex: 191, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 192, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'high', label: 'High', rawIndex: 193, size: 'int1x7', min: -50, max: 50, offset: 50 },
    { key: 'body', label: 'Body', rawIndex: 194, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'low', label: 'Low', rawIndex: 195, size: 'int1x7', min: -50, max: 50, offset: 50 },
    { key: 'level', label: 'Level', rawIndex: 196, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'script', label: 'Script', rawIndex: 197, size: 'int1x7', min: 0, max: 1, offset: 0 },
    { key: 'speed', label: 'Speed', rawIndex: 198, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'manual', label: 'Manual', rawIndex: 199, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'width', label: 'Width', rawIndex: 200, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'speed', label: 'Speed', rawIndex: 201, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'regen', label: 'Regen', rawIndex: 202, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'pedal_pos', label: 'Pedal Pos', rawIndex: 203, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'pedal_min', label: 'Pedal Min', rawIndex: 204, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'pedal_max', label: 'Pedal Max', rawIndex: 205, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'effect_level', label: 'Effect Level', rawIndex: 206, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 207, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'select', label: 'Select', rawIndex: 208, size: 'int1x7', min: 0, max: 1, offset: 0 },
    { key: 'input_volume', label: 'Input Volume', rawIndex: 209, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'chorus_intensity', label: 'Chorus Intensity', rawIndex: 210, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'echo_repeat_rate', label: 'Echo Repeat Rate', rawIndex: 211, size: 'int4x4', min: 40, max: 600, offset: 0 },
    { key: 'echo_intensisty', label: 'Echo Intensisty', rawIndex: 215, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'echo_volume', label: 'Echo Volume', rawIndex: 216, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'tone', label: 'Tone', rawIndex: 217, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'output', label: 'Output', rawIndex: 218, size: 'int1x7', min: 0, max: 1, offset: 0 },
  ],
  [
    { key: '1oct_level', label: '1OCT Level', rawIndex: 219, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: '2oct_level', label: '2OCT Level', rawIndex: 220, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 221, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
  [
    { key: 'pitch', label: 'Pitch', rawIndex: 222, size: 'int1x7', min: -24, max: 24, offset: 24 },
    { key: 'pedal_pos', label: 'Pedal Pos', rawIndex: 223, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'effect_level', label: 'Effect Level', rawIndex: 224, size: 'int1x7', min: 0, max: 100, offset: 0 },
    { key: 'direct_mix', label: 'Direct Mix', rawIndex: 225, size: 'int1x7', min: 0, max: 100, offset: 0 },
  ],
];
